version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./webledge:/app:delegated
    working_dir: /app
    networks:
      - network1
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development

networks:
  network1:
    name: db_default
    external: true