services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./webledge:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      NODE_ENV: development
    networks:
      - network1

networks:
  network1:
    name: db_network
    external: true