FROM golang:1.21.2-alpine AS base

RUN apk add --no-cache make build-base

WORKDIR /tmp
RUN go install github.com/cosmtrek/air@latest && go install github.com/maruel/panicparse@latest

ENV GOFLAGS=-buildvcs=false
ARG APP_ROOT=/app
ENV APP_ROOT=${APP_ROOT}

ENV CGO_ENABLED="1"

RUN mkdir -p ${APP_ROOT}

ADD . ${APP_ROOT}
WORKDIR ${APP_ROOT}

FROM golangci/golangci-lint:latest AS lint-base

FROM base
COPY --from=lint-base /usr/bin/golangci-lint /usr/bin/golangci-lint