FROM golang:1.23-alpine AS base

RUN apk add --no-cache make build-base

WORKDIR /tmp
RUN go install github.com/air-verse/air@latest && go install github.com/maruel/panicparse@latest

RUN mkdir -p /go/cache
RUN chmod 777 /go/cache
ENV GOCACHE=/go/cache/go-build
ENV GOLANGCI_LINT_CACHE=/go/cache/golangci-lint
ENV GOFLAGS=-buildvcs=false
ARG APP_ROOT=/app
ENV APP_ROOT=${APP_ROOT}

ENV CGO_ENABLED="1"

RUN mkdir -p ${APP_ROOT}

ADD . ${APP_ROOT}
WORKDIR ${APP_ROOT}

FROM golangci/golangci-lint:v1.59-alpine AS lint-base

FROM base
COPY --from=lint-base /usr/bin/golangci-lint /usr/bin/golangci-lint